language: cpp
compiler: clang
script: 
- make
- xctool -project "ULog.xcodeproj" -scheme "ULog - Mac Framework" build
- xctool -project "ULog.xcodeproj" -scheme "ULog - Mac Static Library" build
- xctool -project "ULog.xcodeproj" -scheme "ULog - iOS Static Library" build
- xctool -project "Example-Mac.xcodeproj" -scheme "ULog Example - Mac" build
- xctool -project "Example-iOS.xcodeproj" -scheme "ULog Example - iOS" build
sudo: required
dist: trusty
before_install:
- if [ "$TRAVIS_OS_NAME" == "osx" ];   then bash Scripts/travis-osx-before.sh;   fi
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then bash Scripts/travis-linux-before.sh; fi
after_success:
- if [ "$TRAVIS_OS_NAME" == "osx" ];   then bash Scripts/travis-osx-after.sh;   fi
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then bash Scripts/travis-linux-after.sh; fi
os:
  - osx
  - linux
